# ------------------------------------------------------------------------
#
# Copyright (c) 2016, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
#   WSO2 Inc. licenses this file to you under the Apache License,
#   Version 2.0 (the "License"); you may not use this file except
#   in compliance with the License.
#   You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing,
#   software distributed under the License is distributed on an
#   "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#   KIND, either express or implied.  See the License for the
#   specific language governing permissions and limitations
#   under the License.
#
# ------------------------------------------------------------------------
FROM java:8

ENV MSF4J_JAR ARTIFACT_NAME
ENV MSF4J_HOME /srv/msf4j
ENV PATH $MSF4J_HOME:$PATH

RUN mkdir -p "$MSF4J_HOME"
COPY "$MSF4J_JAR" "$MSF4J_HOME/"

WORKDIR $MSF4J_HOME

EXPOSE 8080

CMD ["java", "-jar", "ARTIFACT_NAME"]
