# ------------------------------------------------------------------------
#
# Copyright (c) 2016, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
#   WSO2 Inc. licenses this file to you under the Apache License,
#   Version 2.0 (the "License"); you may not use this file except
#   in compliance with the License.
#   You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing,
#   software distributed under the License is distributed on an
#   "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#   KIND, either express or implied.  See the License for the
#   specific language governing permissions and limitations
#   under the License.
#
# ------------------------------------------------------------------------
FROM tomcat:8.0

ENV APP_WAR ARTIFACT_NAME
ENV WEB_APP_HOME /usr/local/tomcat/webapps/

RUN sed -i "s/unpackWARs=\"true\"/unpackWARs=\"false\"/g" /usr/local/tomcat/conf/server.xml \
        && sed -i "/\/Host/i  \\\t<Context path=\"/\" docBase=\"$APP_WAR\" debug=\"0\" reloadable=\"true\"></Context>" /usr/local/tomcat/conf/server.xml

COPY "$APP_WAR" "$WEB_APP_HOME/"

CMD ["catalina.sh", "run"]
