# ------------------------------------------------------------------------
#
# Copyright (c) 2016, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
#   WSO2 Inc. licenses this file to you under the Apache License,
#   Version 2.0 (the "License"); you may not use this file except
#   in compliance with the License.
#   You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing,
#   software distributed under the License is distributed on an
#   "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#   KIND, either express or implied.  See the License for the
#   specific language governing permissions and limitations
#   under the License.
#
# ------------------------------------------------------------------------

FROM wso2-appcloud/wso2dataservice:3.5.0-base

ENV CARBON_HOME_PATH /opt/wso2dss-3.5.0
ENV DATASERVICE_DBS ARTIFACT_NAME
ENV CAR_DEPLOYMENT_DIR $CARBON_HOME_PATH/repository/deployment/server/carbonapps/
ENV APP_HOST HOST_NAME
ENV TOTAL_MEMORY VAL_TOTAL_MEMORY

RUN mkdir -p $CAR_DEPLOYMENT_DIR

COPY "$DATASERVICE_DBS" "$CAR_DEPLOYMENT_DIR"
RUN sed -i '/<!--HostName>/c\\t<HostName>'$APP_HOST'</HostName>' $CARBON_HOME_PATH/repository/conf/carbon.xml && \
    sed -i '/<!--MgtHostName>/c\\t<MgtHostName>'$APP_HOST'</MgtHostName>' $CARBON_HOME_PATH/repository/conf/carbon.xml

WORKDIR "/"

CMD ["bash", "-c", "source /init.sh"]
